from django.urls import path

from airline.views import (
    user_list,
    plane_list,
    plane_detail,
    user_register,
    user_login,
    flight_list,
    flight_administration,
    edit_user,
    help_view,
    add_status_flight,
    add_passenger,
    select_seat,
    confirm_reservation,
)

urlpatterns = [
    path(
        route='flights/<int:flight_id>/passenger/<int:passenger_id>/seat/<int:seat_id>/confirm/',
        view=confirm_reservation,
        name='confirm_reservation'
    ),
    path(
        route='flightstatus/',
        view=add_status_flight,
        name='add_status_flight'
    ),
    path('flights/<int:flight_id>/add-passenger/', 
         view=add_passenger, 
         name='add_passenger'),
    path('help/', 
         view=help_view, 
         name='help_view'),
    path(
        route='users/edit/<int:user_id>/',
        view=edit_user,
        name='edit_user'
    ),
    path(
        route='flights/<int:flight_id>/passengers/<int:passenger_id>/select-seat/',
        view=select_seat,
        name='select_seat'
    ),
    path(
        route='users/',
        view=user_list,
        name='user_list'
    ),
    path('users/register/', 
         view=user_register, 
         name='user_register'
    ),
    path('users/login/', 
         view=user_login, 
         name='user_login'),
    path(
        route='planes/',
        view=plane_list,
        name='plane_list'
    ),
    path(
        route='planes/details/<int:plane_id>',
        view=plane_detail,
        name='plane_detail'
    ),
    path(
        route='flights/',
        view=flight_list,
        name='flight_list',
    ),
    path(
        route='flights/flight_administration/',
        view=flight_administration,
        name='flight_administration',
    )
]
